# Generated by Django 3.1.2 on 2020-10-12 13:09

from django.db import migrations, models
import django_cryptography.fields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20201012_0956'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=django_cryptography.fields.encrypt(models.CharField(blank=True, max_length=30, null=True, unique=True)),
        ),
    ]
