# Generated by Django 3.1.2 on 2020-10-14 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20201014_1018'),
    ]

    operations = [
        migrations.AddField(
            model_name='invite',
            name='confirmed',
            field=models.BooleanField(default=False),
        ),
    ]
