# Generated by Django 3.1.2 on 2020-10-14 12:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_invite_confirmed'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendee',
            name='invite',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='attendees', to='core.invite'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='attendee',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='invitation', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='invite',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='invites', to=settings.AUTH_USER_MODEL),
        ),
    ]
