# Generated by Django 3.1.2 on 2020-10-15 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20201014_1234'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='attendee',
            options={'ordering': ['ordinal']},
        ),
        migrations.AddField(
            model_name='attendee',
            name='ordinal',
            field=models.PositiveIntegerField(default=1602767016, unique=True),
            preserve_default=False,
        ),
    ]
