# Generated by Django 3.1.2 on 2020-10-15 13:06

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20201015_1303'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendee',
            name='ordinal',
            field=models.PositiveBigIntegerField(default=core.models.default_ordinal),
        ),
    ]
