# Generated by Django 3.1.2 on 2020-10-15 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_auto_20201015_1306'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendee',
            name='confirmed',
            field=models.BooleanField(default=False),
        ),
    ]
