# Generated by Django 3.1.2 on 2020-10-15 15:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_attendee_confirmed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendee',
            name='invite',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='attendees', to='core.invite'),
        ),
    ]
