# Generated by Django 3.1.2 on 2020-10-15 21:31

from django.db import migrations, models
import django_cryptography.fields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_auto_20201015_1517'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='id_number',
            field=django_cryptography.fields.encrypt(models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True)),
        ),
    ]
