# Generated by Django 3.1.2 on 2020-10-17 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_auto_20201015_2131'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendee',
            name='attends_as',
            field=models.IntegerField(choices=[(1, 'Couple'), (2, 'Planner'), (3, 'Bridal Team'), (4, 'Family'), (5, 'Guest'), (6, 'Service Provider')], default=5),
        ),
    ]
