# Generated by Django 3.1.2 on 2020-10-17 15:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_auto_20201017_1252'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendee',
            name='confirmed',
        ),
    ]
