# Generated by Django 3.1.2 on 2020-10-17 16:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_remove_attendee_confirmed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invite',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='invites', to=settings.AUTH_USER_MODEL),
        ),
    ]
