# Generated by Django 3.1.2 on 2020-11-16 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_user_residence'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invite',
            name='confirmed',
        ),
        migrations.AddField(
            model_name='invite',
            name='rsvp',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
