# Generated by Django 3.1.2 on 2020-11-16 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_auto_20201116_1339'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invite',
            name='rsvp',
            field=models.CharField(blank=True, choices=[('yes', 'yes'), ('no', 'no')], max_length=3, null=True),
        ),
    ]
