# Generated by Django 3.1.2 on 2020-11-18 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_auto_20201116_1730'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendee',
            name='attends_as',
            field=models.IntegerField(choices=[(1, 'Couple'), (2, 'Planner'), (3, 'Bridal Team'), (4, 'Family'), (5, 'Guest'), (6, 'Service Provider'), (7, 'Group')], default=5),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
