# Generated by Django 3.1.2 on 2020-11-19 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_auto_20201118_0811'),
    ]

    operations = [
        migrations.AddField(
            model_name='invite',
            name='added_for',
            field=models.IntegerField(choices=[(1, 'Couple'), (2, 'Planner'), (3, 'Bridal Team'), (4, 'Family'), (5, 'Guest'), (6, 'Service Provider'), (7, 'Group'), (8, 'Kids')], default=5),
        ),
        migrations.AlterField(
            model_name='attendee',
            name='attends_as',
            field=models.IntegerField(choices=[(1, 'Couple'), (2, 'Planner'), (3, 'Bridal Team'), (4, 'Family'), (5, 'Guest'), (6, 'Service Provider'), (7, 'Group'), (8, 'Kids')], default=5),
        ),
    ]
