# Generated by Django 3.1.2 on 2020-11-19 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_auto_20201119_0930'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendee',
            name='kids_allowed',
        ),
        migrations.AddField(
            model_name='invite',
            name='kids_allowed',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
