# Generated by Django 3.1.2 on 2020-11-19 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_auto_20201119_0933'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invite',
            name='kids_allowed',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
