# Generated by Django 3.1.2 on 2020-12-02 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_auto_20201119_0950'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendee',
            name='seat',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
