# Generated by Django 3.1.2 on 2020-12-02 21:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_attendee_seat'),
    ]

    operations = [
        migrations.RenameField(
            model_name='attendee',
            old_name='seat',
            new_name='table',
        ),
    ]
